[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
backyard_programs = "EyQQodCfDanyQooK9D1ixJsEUPDmN7H8fghBJ4bGM1d8"

[programs.devnet]
backyard_programs = "EyQQodCfDanyQooK9D1ixJsEUPDmN7H8fghBJ4bGM1d8"

[programs.mainnet]
backyard_programs = "EyQQodCfDanyQooK9D1ixJsEUPDmN7H8fghBJ4bGM1d8"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/backyard-id.json"

[scripts]
test = "yarn run jest --preset ts-jest"
